version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=product_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=product
      - MYSQL_PASSWORD=product
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d